FAKE-129 - Added null promote message check/cancellation; added automatic prepare-commit-msg script

diff --git a/git-jira b/git-jira
--- a/git-jira
+++ b/git-jira
@@ -1,5 +1,125 @@
 #!/bin/bash -e
 
+function _write_precommit_script () {
+	local SCRIPT_NAME=/tmp/prepare-commit-msg-$RANDOM
+	cat << 'EOF' > $SCRIPT_NAME
+#!/bin/bash -e
+
+COMMIT_FILE=$1
+
+. git-sh-setup
+
+CACHE_FILE=$GIT_DIR/jira.cache
+
+JIRA_SERVER=$(git config jira.server || true)
+JIRA_USER=$(git config jira.user || true)
+JIRA_PASSWORD=$(git config jira.password || true)
+JIRA_PREFIX=$(git config jira.prefix || true)
+
+JIRA_COMMIT_TEMPLATE=$(git config jira.commit.template || true)
+
+JIRA_CLI=$(git config jira.cli || true)
+
+JIRA_CMD="$JIRA_CLI --server $JIRA_SERVER --user $JIRA_USER --password $JIRA_PASSWORD"
+
+function prepend () {
+	local MSG=$1
+	# Give up if we already have a commit message (like when rebasing)
+	awk 'NR==1 && /^$/ { exit 0 }; {exit 1} ' < $COMMIT_FILE || return 0
+
+	echo -e $MSG | sed -i '' -e "1s/^/\
+# [jira]/" -e 'r /dev/stdin' -e '2s/^/# \
+/' $COMMIT_FILE
+}
+
+function prepend_ok () {
+	local MSG=$1
+	# Give up if we already have a commit message (like when rebasing)
+	awk 'NR==1 && /^$/ { exit 0 }; {exit 1} ' < $COMMIT_FILE || return 0
+
+	echo -e $MSG | sed -i '' -e 'r /dev/stdin' -e '1d' -e '2s/^//' $COMMIT_FILE
+}
+
+function get_cached_issue () {
+	local ISSUE=$1
+	test -f $CACHE_FILE || return 0
+	local LINE=`grep ^$ISSUE: $CACHE_FILE`
+	test -n "$LINE" || return 0
+	ISSUE_SUMMARY=$(echo $LINE | sed -e "s/^$ISSUE: //")
+}
+
+function fail () {
+	echo $@
+	exit 1
+}
+
+# start to work
+
+require_work_tree
+
+test -n "$GIT_DIR" || fail "Missing GIT_DIR variable"
+test -n "$COMMIT_FILE" || fail "Missing commit file argument"
+test -n "$JIRA_SERVER" || fail "Missing git config variable jira.server (set it with 'git config jira.server ...')"
+test -n "$JIRA_CLI" || fail "Missing git config variable jira.cli (set it with 'git config jira.cli ...')"
+test -n "$JIRA_USER" || fail "Missing git config variable jira.user (set it with 'git config jira.user ...')"
+test -n "$JIRA_PASSWORD" || fail "Missing git config variable jira.password (set it with 'git config jira.password ...')"
+test -n "$JIRA_PREFIX" || fail "Missing git config variable jira.prefix (set it with 'git config jira.prefix ...')"
+test -n "$JIRA_COMMIT_TEMPLATE" || JIRA_COMMIT_TEMPLATE="%i - Remove leading hash and provide description"
+
+BRANCH_NAME=$(git symbolic-ref HEAD | sed -e 's/refs\/heads\///')
+
+if [ -z "$BRANCH_NAME" ]; then
+	prepend "# Not committing from a branch"
+	exit 0
+fi
+
+# is the branch a JIRA key?
+if [[ ! ( $BRANCH_NAME =~ ^[A-Z]+-[0-9]+$ ) ]]; then
+	prepend "# Branch does not appear to be a JIRA issue"
+	exit 0
+fi
+
+get_cached_issue $BRANCH_NAME
+
+if [ -z "$ISSUE_SUMMARY" ]; then
+	echo "Querying JIRA, this might take a while..."
+	ISSUE_SUMMARY=`$JIRA_CMD --action getFieldValue --issue $BRANCH_NAME --field Summary | sed -e '1d'`
+	SHOULD_CACHE=1
+fi
+
+if [ -z "$ISSUE_SUMMARY" ]; then
+	prepend "# Branch appears to be a JIRA issue but we were unable to get its description"
+	exit 0
+fi
+
+if [ "$SHOULD_CACHE" = "1" ]; then
+	echo "$BRANCH_NAME: $ISSUE_SUMMARY" >> $CACHE_FILE
+fi
+
+TEMPLATE=$(echo "$JIRA_COMMIT_TEMPLATE" | awk -v i="$BRANCH_NAME" -v t="$ISSUE_SUMMARY" '{sub(/%i/,i); sub(/%t/,t); print}')
+prepend_ok "#$TEMPLATE\n#\n# This branch is associated with the following JIRA issue:\n#\t[$BRANCH_NAME] $ISSUE_SUMMARY\n# View this issue at $JIRA_SERVER/browse/$BRANCH_NAME\n#"
+EOF
+
+	if $(diff "$GIT_DIR/hooks/prepare-commit-msg" "$SCRIPT_NAME" >/dev/null 2>/dev/null); then
+		: # do nothing
+	else
+		printf "The JIRA git extension requires a modified \"prepare-commit-msg\" hook.\n"
+		printf "It appears that it has not yet been installed or is out of date with the\n"
+		printf "needed version. We can update it for you automatically.\n\n"
+
+		read -e -p "Install updated hook [yes]: " ans2
+		ans2=$(echo $ans2 | tr [a-z] [A-Z])
+
+		if [ $ans2 == "YES" -o \
+			$ans2 == "Y" -o \
+			-z $ans2 ]; then
+			cp "$SCRIPT_NAME" "$GIT_DIR/hooks/prepare-commit-msg"
+
+			echo "Hook updated."
+		fi
+	fi
+}
+
 # git required variables
 USAGE='<command> [<args>]
 
@@ -22,6 +142,9 @@ commits and customized notes.'
 
 # Sets GIT_DIR and GIT_OBJECT_DIRECTORY, and provides functions below
 . git-sh-setup
+
+# Check for updated precommit script
+_write_precommit_script
 
 # Setup
 GIT_KEY_JIRA_CLI="jira.cli"
@@ -232,20 +355,23 @@ case "$ACTION" in
 		printf "\n; Provide any additional information you want to include in the JIRA ticket\n" >> $NOTES_FILE
 		printf "; comment here. Lines that begin with a semicolon (;) will be ignored. Note\n" >> $NOTES_FILE
 		printf "; that you should not intentionally use line breaks, as JIRA will word-wrap\n" >> $NOTES_FILE
-		printf "; for you.\n" >> $NOTES_FILE
+		printf "; for you. An empty message aborts the promote.\n" >> $NOTES_FILE
 
 		${EDITOR:-vi} "$NOTES_FILE"
-		NOTES=$(cat "$NOTES_FILE" | sed -e '/;.*/d') # Remove comments and blank new lines
+		NOTES=$(cat "$NOTES_FILE" | sed -e '/;.*/d') # Remove comments
+		NOTES_TRIMMED=$(echo "$NOTES" | sed -e '/^$/d') # Remove newlines, just to see if there's anything there
+
 		rm "$NOTES_FILE"
 
-		printf "\n\nMerging branch $BRANCH_NAME into $TARGET_MERGE_BRANCH..."
+		if [ ! -z $NOTES_TRIMMED ]; then
+			printf "\n\nMerging branch $BRANCH_NAME into $TARGET_MERGE_BRANCH..."
 
-		# The following reduces git log messages down to oneline--multiline
-		# commits are not an issue
-		COMMITS=$(git log $TARGET_MERGE_BRANCH.. --oneline --no-abbrev-commit | sed \
-			-e "s/\([0-9a-f]*\) \(.*\)/* \[\2|http:\/\/hidef.beanstalkapp.com\/$BEANSTALK_REPOSITORY\/changesets\/\1\]/" \
-			-e "s/$BRANCH_NAME - //")
-		COMMIT_MSG="(i) *This should now be available for testing.*
+			# The following reduces git log messages down to oneline--multiline
+			# commits are not an issue
+			COMMITS=$(git log $TARGET_MERGE_BRANCH.. --oneline --no-abbrev-commit | sed \
+				-e "s/\([0-9a-f]*\) \(.*\)/* \[\2|http:\/\/hidef.beanstalkapp.com\/$BEANSTALK_REPOSITORY\/changesets\/\1\]/" \
+				-e "s/$BRANCH_NAME - //")
+			COMMIT_MSG="(i) *This should now be available for testing.*
 
 The following code commits have been made to address this issue:
 
@@ -253,26 +379,29 @@ $COMMITS
 
 $NOTES
 "
-		git checkout $BRANCH_NAME
-		git rebase $TARGET_MERGE_BRANCH
-		git checkout $TARGET_MERGE_BRANCH
-		git merge $BRANCH_NAME
+			git checkout $BRANCH_NAME
+			git rebase $TARGET_MERGE_BRANCH
+			git checkout $TARGET_MERGE_BRANCH
+			git merge $BRANCH_NAME
 
-		printf "\nUpdating JIRA...\n"
+			printf "\nUpdating JIRA...\n"
 
-		$JIRA_CMD --action progressIssue --issue $BRANCH_NAME --step "Promote"
-		$JIRA_CMD --action addComment --issue $BRANCH_NAME --comment "$COMMIT_MSG"
+			$JIRA_CMD --action progressIssue --issue $BRANCH_NAME --step "Promote"
+			$JIRA_CMD --action addComment --issue $BRANCH_NAME --comment "$COMMIT_MSG"
 
-		read -e -p "Delete local issue branch $BRANCH_NAME [y]: " ans
-		ans=$(echo $ans | tr [a-z] [A-Z])
+			read -e -p "Delete local issue branch $BRANCH_NAME [y]: " ans
+			ans=$(echo $ans | tr [a-z] [A-Z])
 
-		if [ -z $ans -o \
-			$ans == "Y" -o \
-			$ans == "YES" ]; then
-			git branch -d $BRANCH_NAME
+			if [ -z $ans -o \
+				$ans == "Y" -o \
+				$ans == "YES" ]; then
+				git branch -d $BRANCH_NAME
+			fi
+
+			echo "Done!"
+		else
+			echo "Aborting promote due to empty promotion message."
 		fi
-
-		echo "Done!"
 	;;
 
 	*) echo "$USAGE" ;;
